In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("C:\\Users\\srnva\\Desktop\\UDEMY\\UPDATED_NLP_COURSE\\TextFiles\\smsspamcollection.tsv", sep="\t")
df.head()

label                                            message  length  punct
0   ham  Go until jurong point, crazy.. Available only ...     111      9
1   ham                      Ok lar... Joking wif u oni...      29      6
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...     155      6
3   ham  U dun say so early hor... U c already then say...      49      6
4   ham  Nah I don't think he goes to usf, he lives aro...      61      2

In [4]:
df.isnull().sum()

label      0
message    0
length     0
punct      0
dtype: int64

In [5]:
len(df)

5572

In [6]:
df['label'].value_counts()

ham     4825
spam     747
Name: label, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split

In [10]:
X = df[['length', 'punct']]
y = df['label']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [13]:
X_train.shape

(3900, 2)

## Logistic Regression

In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
lr = LogisticRegression(solver='lbfgs')

In [16]:
model = lr.fit(X_train, y_train)

In [17]:
predictions = lr.predict(X_test)

In [22]:
from sklearn.metrics import classification_report, confusion_matrix

In [28]:
print(metrics.classification_report(y_test, predictions))

              precision    recall  f1-score   support

         ham       0.87      0.97      0.91      1448
        spam       0.10      0.02      0.04       224

    accuracy                           0.84      1672
   macro avg       0.48      0.50      0.48      1672
weighted avg       0.76      0.84      0.80      1672



In [26]:
print(confusion_matrix(y_test, predictions))

[[1404   44]
 [ 219    5]]


In [27]:
data_f = pd.DataFrame(confusion_matrix(y_test, predictions), index=['ham', 'spam'], columns=['ham', 'spam'])
data_f

ham  spam
ham   1404    44
spam   219     5

In [29]:
print(metrics.accuracy_score(y_test, predictions))

0.8427033492822966


## Naive Bayes

In [30]:
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()
nb.fit(X_train, y_train)
pred = nb.predict(X_test)
print(confusion_matrix(y_test, pred))

[[1438   10]
 [ 224    0]]


In [31]:
print(metrics.classification_report(y_test, pred))

              precision    recall  f1-score   support

         ham       0.87      0.99      0.92      1448
        spam       0.00      0.00      0.00       224

    accuracy                           0.86      1672
   macro avg       0.43      0.50      0.46      1672
weighted avg       0.75      0.86      0.80      1672



## SVC

In [32]:
from sklearn.svm import SVC

In [33]:
sm = SVC(gamma='auto')
sm.fit(X_train, y_train)
predicted = sm.predict(X_test)
print(confusion_matrix(y_test, predicted))

[[1373   75]
 [ 121  103]]


In [34]:
print(metrics.classification_report(y_test, predicted))

              precision    recall  f1-score   support

         ham       0.92      0.95      0.93      1448
        spam       0.58      0.46      0.51       224

    accuracy                           0.88      1672
   macro avg       0.75      0.70      0.72      1672
weighted avg       0.87      0.88      0.88      1672



## Text Extraction

In [35]:
X = df['message']
y = df['label']

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

In [39]:
vec = CountVectorizer()

In [47]:
X_train_counts = vec.fit_transform(X_train)

In [48]:
X_train_counts

<3733x7082 sparse matrix of type '<class 'numpy.int64'>'
	with 49992 stored elements in Compressed Sparse Row format>

In [49]:
X_train.shape

(3733,)

In [50]:
X_train_counts.shape

(3733, 7082)

In [51]:
vectorizer = TfidfVectorizer()

In [52]:
X_train_tfidf = vectorizer.fit_transform(X_train)

In [53]:
from sklearn.svm import LinearSVC

In [54]:
clf = LinearSVC()

In [55]:
clf.fit(X_train_tfidf, y_train)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [57]:
from sklearn.pipeline import Pipeline

In [59]:
text_clf = Pipeline([('tfidf',TfidfVectorizer()), ('clf',LinearSVC())])

In [60]:
text_clf.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('clf',
                 LinearSVC(C=1.0, class_weight=None, dual=True,
                           fit_intercept=True, intercept_scaling=1,
               

In [62]:
prediction = text_clf.predict(X_test)

In [63]:
print(confusion_matrix(y_test, prediction))

[[1586    7]
 [  12  234]]


In [64]:
print(metrics.classification_report(y_test, prediction))

              precision    recall  f1-score   support

         ham       0.99      1.00      0.99      1593
        spam       0.97      0.95      0.96       246

    accuracy                           0.99      1839
   macro avg       0.98      0.97      0.98      1839
weighted avg       0.99      0.99      0.99      1839



In [65]:
print(metrics.accuracy_score(y_test, prediction))

0.989668297988037


In [68]:
text_clf.predict(["Hi! How are you doing today?"])

array(['ham'], dtype=object)

In [70]:
text_clf.predict(["Congratulations! you won a lottery worth $2 million. Please register to collect"])

array(['spam'], dtype=object)